# ===============================
# DATABASE
# ===============================

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testdb2555
        username: root
        password: root
