# ===============================
# DATABASE
# ===============================

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testDB
        username: root
        password: root
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: update
